# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dynscreen.ui'
#
# Created: Thu May 31 20:40:49 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainScreen(object):
    def setupUi(self, MainScreen):
        MainScreen.setObjectName(_fromUtf8("MainScreen"))
        MainScreen.setWindowModality(QtCore.Qt.NonModal)
        MainScreen.setEnabled(True)
        MainScreen.resize(914, 793)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainScreen.setPalette(palette)
        MainScreen.setAutoFillBackground(False)
        self.gridLayout = QtGui.QGridLayout(MainScreen)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.labelStation = QtGui.QLabel(MainScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelStation.sizePolicy().hasHeightForWidth())
        self.labelStation.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelStation.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.labelStation.setFont(font)
        self.labelStation.setAutoFillBackground(False)
        self.labelStation.setScaledContents(False)
        self.labelStation.setAlignment(QtCore.Qt.AlignCenter)
        self.labelStation.setObjectName(_fromUtf8("labelStation"))
        self.verticalLayout_2.addWidget(self.labelStation)
        self.labelSlogan = QtGui.QLabel(MainScreen)
        self.labelSlogan.setSizeIncrement(QtCore.QSize(1, 1))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(146, 145, 144))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.labelSlogan.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelSlogan.setFont(font)
        self.labelSlogan.setAutoFillBackground(False)
        self.labelSlogan.setScaledContents(False)
        self.labelSlogan.setAlignment(QtCore.Qt.AlignCenter)
        self.labelSlogan.setObjectName(_fromUtf8("labelSlogan"))
        self.verticalLayout_2.addWidget(self.labelSlogan)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.buttonLED1 = QtGui.QPushButton(MainScreen)
        self.buttonLED1.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLED1.sizePolicy().hasHeightForWidth())
        self.buttonLED1.setSizePolicy(sizePolicy)
        self.buttonLED1.setMinimumSize(QtCore.QSize(220, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.buttonLED1.setFont(font)
        self.buttonLED1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonLED1.setAutoFillBackground(False)
        self.buttonLED1.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.buttonLED1.setCheckable(False)
        self.buttonLED1.setAutoDefault(False)
        self.buttonLED1.setDefault(False)
        self.buttonLED1.setFlat(False)
        self.buttonLED1.setObjectName(_fromUtf8("buttonLED1"))
        self.verticalLayout.addWidget(self.buttonLED1)
        spacerItem = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLED2 = QtGui.QPushButton(MainScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLED2.sizePolicy().hasHeightForWidth())
        self.buttonLED2.setSizePolicy(sizePolicy)
        self.buttonLED2.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.buttonLED2.setFont(font)
        self.buttonLED2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonLED2.setStyleSheet(_fromUtf8("background-color: rgb(220, 220, 0);\n"
"color: rgb(255, 255, 255);"))
        self.buttonLED2.setObjectName(_fromUtf8("buttonLED2"))
        self.verticalLayout.addWidget(self.buttonLED2)
        spacerItem1 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonLED3 = QtGui.QPushButton(MainScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLED3.sizePolicy().hasHeightForWidth())
        self.buttonLED3.setSizePolicy(sizePolicy)
        self.buttonLED3.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.buttonLED3.setFont(font)
        self.buttonLED3.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonLED3.setStyleSheet(_fromUtf8("background-color: rgb(0, 200, 200);\n"
"color: rgb(255, 255, 255);"))
        self.buttonLED3.setObjectName(_fromUtf8("buttonLED3"))
        self.verticalLayout.addWidget(self.buttonLED3)
        spacerItem2 = QtGui.QSpacerItem(20, 5, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.MinimumExpanding)
        self.verticalLayout.addItem(spacerItem2)
        self.buttonLED4 = QtGui.QPushButton(MainScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLED4.sizePolicy().hasHeightForWidth())
        self.buttonLED4.setSizePolicy(sizePolicy)
        self.buttonLED4.setMinimumSize(QtCore.QSize(0, 150))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.buttonLED4.setFont(font)
        self.buttonLED4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.buttonLED4.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 255);\n"
"color: rgb(255, 255, 255);"))
        self.buttonLED4.setObjectName(_fromUtf8("buttonLED4"))
        self.verticalLayout.addWidget(self.buttonLED4)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 10)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 10)
        self.gridLayout.addLayout(self.verticalLayout, 1, 4, 6, 1)
        self.progressL = QtGui.QProgressBar(MainScreen)
        self.progressL.setStyleSheet(_fromUtf8("selection-background-color: rgb(0, 255, 0);\n"
"background-color: rgb(42, 42, 42);"))
        self.progressL.setMaximum(127)
        self.progressL.setProperty("value", 24)
        self.progressL.setTextVisible(False)
        self.progressL.setOrientation(QtCore.Qt.Vertical)
        self.progressL.setObjectName(_fromUtf8("progressL"))
        self.gridLayout.addWidget(self.progressL, 1, 0, 5, 1)
        self.progressR = QtGui.QProgressBar(MainScreen)
        self.progressR.setAutoFillBackground(False)
        self.progressR.setStyleSheet(_fromUtf8("selection-background-color: rgb(0, 255, 0);\n"
"background-color: rgb(42, 42, 42);"))
        self.progressR.setMaximum(127)
        self.progressR.setProperty("value", 24)
        self.progressR.setTextVisible(False)
        self.progressR.setOrientation(QtCore.Qt.Vertical)
        self.progressR.setObjectName(_fromUtf8("progressR"))
        self.gridLayout.addWidget(self.progressR, 1, 1, 5, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.oasanalogclockWidget = OASAnalogClockWidget(MainScreen)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.oasanalogclockWidget.sizePolicy().hasHeightForWidth())
        self.oasanalogclockWidget.setSizePolicy(sizePolicy)
        self.oasanalogclockWidget.setMinimumSize(QtCore.QSize(512, 0))
        self.oasanalogclockWidget.setObjectName(_fromUtf8("oasanalogclockWidget"))
        self.verticalLayout_3.addWidget(self.oasanalogclockWidget)
        self.labelClock = QtGui.QLabel(MainScreen)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(72)
        font.setBold(True)
        font.setWeight(75)
        self.labelClock.setFont(font)
        self.labelClock.setStyleSheet(_fromUtf8("color: rgb(255, 255, 0)"))
        self.labelClock.setAlignment(QtCore.Qt.AlignCenter)
        self.labelClock.setObjectName(_fromUtf8("labelClock"))
        self.verticalLayout_3.addWidget(self.labelClock)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 2, 5, 2)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.labelTextLeft = QtGui.QLabel(MainScreen)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.labelTextLeft.setFont(font)
        self.labelTextLeft.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.labelTextLeft.setObjectName(_fromUtf8("labelTextLeft"))
        self.horizontalLayout.addWidget(self.labelTextLeft)
        self.labelTextRight = QtGui.QLabel(MainScreen)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.labelTextRight.setFont(font)
        self.labelTextRight.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.labelTextRight.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelTextRight.setObjectName(_fromUtf8("labelTextRight"))
        self.horizontalLayout.addWidget(self.labelTextRight)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 0, 1, 4)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.labelCurrentSong = QtGui.QLabel(MainScreen)
        self.labelCurrentSong.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.labelCurrentSong.setFont(font)
        self.labelCurrentSong.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.labelCurrentSong.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrentSong.setObjectName(_fromUtf8("labelCurrentSong"))
        self.verticalLayout_4.addWidget(self.labelCurrentSong)
        self.labelNews = QtGui.QLabel(MainScreen)
        self.labelNews.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.labelNews.setFont(font)
        self.labelNews.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.labelNews.setAlignment(QtCore.Qt.AlignCenter)
        self.labelNews.setObjectName(_fromUtf8("labelNews"))
        self.verticalLayout_4.addWidget(self.labelNews)
        self.gridLayout.addLayout(self.verticalLayout_4, 7, 0, 1, 5)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 4)
        self.gridLayout.setColumnStretch(4, 2)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(MainScreen)
        QtCore.QMetaObject.connectSlotsByName(MainScreen)

    def retranslateUi(self, MainScreen):
        MainScreen.setWindowTitle(QtGui.QApplication.translate("MainScreen", "OnAirScreen", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStation.setText(QtGui.QApplication.translate("MainScreen", "labelStation", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSlogan.setText(QtGui.QApplication.translate("MainScreen", "labelSlogan", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLED1.setText(QtGui.QApplication.translate("MainScreen", "buttonLED1", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLED2.setText(QtGui.QApplication.translate("MainScreen", "buttonLED2", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLED3.setText(QtGui.QApplication.translate("MainScreen", "buttonLED3", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonLED4.setText(QtGui.QApplication.translate("MainScreen", "buttonLED4", None, QtGui.QApplication.UnicodeUTF8))
        self.labelClock.setText(QtGui.QApplication.translate("MainScreen", "23:42:05", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTextLeft.setText(QtGui.QApplication.translate("MainScreen", "labelTextLeft", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTextRight.setText(QtGui.QApplication.translate("MainScreen", "labelTextRight", None, QtGui.QApplication.UnicodeUTF8))
        self.labelCurrentSong.setText(QtGui.QApplication.translate("MainScreen", "labelCurrentSong", None, QtGui.QApplication.UnicodeUTF8))
        self.labelNews.setText(QtGui.QApplication.translate("MainScreen", "labelNews", None, QtGui.QApplication.UnicodeUTF8))

from oasanalogclockwidget import OASAnalogClockWidget
